version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html/develop
permissions:
  - object: /var/www/html/develop
    pattern: "**"
    owner: www-data
    group: www-data
hooks:
    BeforeInstall:
        - location: scripts/BeforeInstall.sh
    AfterInstall:
        - location: scripts/AfterInstall.sh